modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory
license="MIT"
issueTrackerURL="https://github.com/Nearata/OptifineCapes/issues" #optional
[[mods]] #mandatory
modId="optifinecapes" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Optifine Capes" #mandatory
logoFile="logo.png" #optional
authors="Nearata" #optional
description="For those who are only interested in the optifine capes."
[[dependencies.optifinecapes]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="CLIENT"
