modLoader="javafml"
loaderVersion="[29,)"
license="MIT"
issueTrackerURL="https://github.com/Nearata/OptifineCapes/issues"
[[mods]]
    modId="optifinecapes"
    version="${file.jarVersion}"
    displayName="Optifine Capes"
    authors="Nearata"
    description="For those who are only interested in the optifine capes."
    logoFile="logo.png"
[[dependencies.optifinecapes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,1.16)"
    ordering="NONE"
    side="CLIENT"
