modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="Unlicense" #mandatory
issueTrackerURL="https://github.com/Nearata/OptifineCapes/issues" #optional

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
logoFile="logo.png" #optional
authors="${mod_authors}" #optional
description="${mod_description}"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"
