modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory
license="Unlicense" #mandatory
issueTrackerURL="https://github.com/Nearata/OptifineCapes/issues" #optional

[[mods]] #mandatory
modId="optifinecapes" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Optifine Capes" #mandatory
logoFile="logo.png" #optional
authors="Nearata" #optional
description="For those who are only interested in the optifine capes."

[[dependencies.optifinecapes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="CLIENT"
